Repository Remmeauth/block-producers-directory-front, pull requests merged in 2019-09, with the labels that each got.

#84 Improve the UI for the index page
  src/components/pages/IndexPage.vue
Labels: component-page, component-ui

#85 Implements Google ReCaptcha to sign up page
  package.json
  src/components/pages/SignUpPage.vue
Labels: component-page, component-ui

#86 Improve the UI for the setting page, BP creation and edition pages
  package-lock.json
  package.json
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/PasswordRecoveringIdentifierPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
  src/components/pages/UserPage.vue
  src/plugins/vuetify.js
Labels: component-page, component-ui

#88 Improve the UI for the header component page
  src/components/common/Header.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/PasswordRecoveringIdentifierPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
  src/components/pages/UserPage.vue
Labels: component-page, component-ui

#91 Add markdown editor to the page for creating and updating BP, and settings page
  package-lock.json
  package.json
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/SettingsPage.vue
Labels: component-ui

#92 Change header component, improve pages design
  src/components/common/Header.vue
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
  src/components/pages/UserPage.vue
Labels: component-page, component-ui

#93 Add block producer status: active, moderation or rejected
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/UserPage.vue
  src/store/modules/blockProducer.js
Labels: enhancement

#94 Implement UI for the changing user password component
  src/components/pages/SettingsPage.vue
  src/store/modules/password.js
Labels: action, component-ui, enhancement

#96 Implement UI for the changing user email address component
  src/components/pages/SettingsPage.vue
  src/forms/pages/user/settings.js
  src/store/index.js
  src/store/modules/email.js
Labels: action, component-ui, enhancement

#97 Add handling of authentication error messages
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
  src/forms/pages/authentication/signIn.js
  src/forms/pages/authentication/signUp.js
  src/store/modules/authentication.js
  src/store/modules/password.js
Labels: component-ui

#98 Implement a UI to delete a block producer component
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/UserPage.vue
  src/store/modules/blockProducer.js
Labels: action, component-ui, enhancement

#99 Implement a UI to delete a user account component
  src/components/common/Header.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/SettingsPage.vue
  src/store/modules/profile.js
Labels: action, component-ui, enhancement

#102 Add a limit on the size of uploaded images, add images to markdown editor, improve block producers filter
  src/App.vue
  src/components/common/Header.vue
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/UserPage.vue
Labels: component-page, component-ui
