Repository Remmeauth/block-producers-directory-front, pull requests merged in 2019-08, with the labels that each got.

#42 Implement block producer page and component
  src/App.vue
  src/components/pages/BlockProducerPage.vue
  src/routes.js
  src/store/index.js
  src/store/modules/blockProducer.js
Labels: component-page, enhancement

#43 Implement settings page
  src/components/pages/SettingsPage.vue
  src/routes.js
  src/store/index.js
  src/store/modules/authentication.js
  src/store/modules/profile.js
  src/store/modules/settings.js
  src/store/modules/user.js
Labels: component-page, enhancement

#49 Implement block producers search component
  src/components/pages/IndexPage.vue
  src/store/modules/blockProducer.js
Labels: action, enhancement

#50 Implement getting likes, put and remove like, is liked by user actions
  src/components/pages/BlockProducerPage.vue
  src/store/index.js
  src/store/modules/authentication.js
  src/store/modules/like.js
Labels: action, enhancement

#51 Implement getting and creating block producers comments component
  src/components/pages/BlockProducerPage.vue
  src/store/index.js
  src/store/modules/comment.js
Labels: action, enhancement

#53 Implement getting block producers comments numbers
  src/components/pages/IndexPage.vue
  src/store/modules/comment.js
Labels: action, enhancement

#54 Implement getting block producers likes numbers
  src/components/pages/IndexPage.vue
  src/store/modules/like.js
Labels: action, enhancement

#56 Implement header: sign in, sign up
  public/index.html
  src/components/common/Header.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
  src/main.js
  src/routes.js
  src/store/modules/blockProducer.js
  src/store/modules/blockProducerCreation.js
  src/store/modules/comment.js
  src/store/modules/like.js
  src/store/modules/settings.js
  src/store/modules/user.js
Labels: component-ui

#57 Implement 404 error and 500 error component, add environment variable for back-end
  .env.development
  .env.production
  README.md
  app.json
  docker-compose.development.yml
  src/assets/icon-sad-face.png
  src/components/pages/BlockProducerPage.vue
  src/components/ui/Error404.vue
  src/components/ui/Error500.vue
  src/store/modules/blockProducer.js
Labels: component-ui, enhancement

#59 Implement UI for block producer page
  package-lock.json
  public/index.html
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/plugins/vuetify.js
  src/routes.js
  src/store/modules/blockProducer.js
  src/store/modules/comment.js
  src/store/modules/like.js
Labels: component-ui

#60 Implement UI for user page
  src/components/common/Header.vue
  src/components/common/User.vue
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/UserPage.vue
  src/routes.js
  src/store/modules/blockProducer.js
  src/store/modules/blockProducerCreation.js
  src/store/modules/profile.js
  src/store/modules/settings.js
  src/store/modules/user.js
  src/store/modules/userPage.js
Labels: component-page, component-ui

#61 Implement UI component for index page
  src/components/common/Header.vue
  src/components/pages/IndexPage.vue
Labels: component-page, component-ui

#64 Implements UI for user settings
  src/components/pages/SettingsPage.vue
  src/store/index.js
  src/store/modules/avatar.js
Labels: component-ui

#65 Implement UI for submitting block producer
  src/components/common/Header.vue
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/SettingsPage.vue
  src/routes.js
  src/store/modules/avatar.js
  src/store/modules/blockProducerCreation.js
Labels: component-ui

#66 Implement UI for editing block producer
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/SettingsPage.vue
  src/store/modules/blockProducer.js
Labels: component-page, component-ui

#68 Render 404 page for non-existing routes
  src/routes.js
Labels: component-page, component-ui

#67 Implement UI for sign in and sign up pages
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
Labels: component-page, component-ui

#71 Implementing a UI for password recovery and password recovery request component
  src/assets/email.png
  src/assets/email_to.png
  src/assets/key.png
  src/assets/remme.png
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/PasswordRecoveringIdentifierPage.vue
  src/components/pages/SignInPage.vue
  src/main.js
  src/routes.js
  src/store/index.js
  src/store/modules/password.js
Labels: action, component-page, component-ui, enhancement

#72 Implemented snackbars, fixed user avatars
  src/components/common/Header.vue
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/UserPage.vue
  src/store/modules/avatar.js
  src/store/modules/profile.js
Labels: action, component-ui

#73 Implement UI for footer component
  src/App.vue
  src/components/common/Footer.vue
Labels: component-ui

#75 Implements validation form for BP submitting
  package.json
  src/components/pages/BlockProducerCreationPage.vue
  src/forms/pages/blockProducer/submit.js
Labels: validation

#78 Remove constanted URL to back-end to environment variable
  src/store/modules/password.js
Labels: bug

#80 Add touch forms before submit button
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
Labels: bug

#79 Implements a validation form for user settings component
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/SettingsPage.vue
  src/forms/pages/blockProducer/submit.js
  src/forms/pages/user/settings.js
Labels: component-ui

#76 Implements a validation form for editing block producer
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/SettingsPage.vue
  src/forms/pages/blockProducer/edit.js
  src/forms/pages/blockProducer/submit.js
Labels: component-ui, enhancement

#82 Fix pseudo redirect headers buttons
  src/components/common/Header.vue
  src/components/pages/BlockProducerCreationPage.vue
  src/components/pages/BlockProducerEditionPage.vue
  src/components/pages/BlockProducerPage.vue
  src/components/pages/IndexPage.vue
  src/components/pages/PasswordRecoverPage.vue
  src/components/pages/PasswordRecoveringIdentifierPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/SignInPage.vue
  src/components/pages/SignUpPage.vue
  src/components/pages/UserPage.vue
  src/main.js
Labels: bug

#83 Improve the UI for the user profile and block producer page
  public/index.html
  src/components/pages/BlockProducerPage.vue
  src/components/pages/SettingsPage.vue
  src/components/pages/UserPage.vue
Labels: component-page, component-ui
